### ISSUE TITLE
host.Unmount doesn't actually unmount

### ISSUE THREAD

**Issue by ncw** [billziss-gh/cgofuse#7] opened 2017-04-29 16:49 UTC
From host.go

```go
// Mount unmounts a file system.
func (host *FileSystemHost) Unmount() {
	if nil != host.fuse {
		C.fuse_exit(host.fuse)
	}
}
```

However according to the fuse docs [fuse_exit](http://libfuse.github.io/doxygen/fuse_8h.html#a9024935b211288c1869dc7566895d739) just stops the event loop, it doesn't do an unmount.

So this method should probably be renamed "Stop" or something like that.

An Unmount method would be really useful though.  Here is how bazil/fuse does it for [linux](https://github.com/bazil/fuse/blob/master/unmount_linux.go) and [everyone else](https://github.com/bazil/fuse/blob/master/unmount_std.go).  I'm guessing a different procedure would be needed for Windows.

**Comment by ncw** [comment] 2017-04-29 16:50
Just realised that this is very much related to #6!

**Comment by billziss-gh** [comment] 2017-04-29 18:24
As you mention this is a duplicate of #6. So let's continue this discussion there.

Thanks for the bazil/fuse links. They could prove useful.

**Closed** 2017-04-29 18:25 UTC
Labels: duplicate
