### ISSUE TITLE
Not able to do file listing using memfs on Windows Server 2008 R2

### ISSUE THREAD

**Issue by mohankumarv2005** [billziss-gh/cgofuse#42] opened 2019-11-19 05:16 UTC
Hi,

On Windows Server 2008 R2, I tried to mount memfs.exe and after creating a folder let's say "F1", it is not allowing to browse/ls the created folder. I get an error as attached.
![Issue](https://user-images.githubusercontent.com/34312022/69118475-a9125580-0ab9-11ea-9353-659c86bf2c95.png)

I see this issue on other Operating Systems like Windows 2012 R2 & few Windows 10 machines as well.

Thanks,
Mohan

**Comment by billziss-gh** [comment] 2019-11-19 05:25
This really depends on the scenario that you want to enable, but for MEMFS the easiest might be to start the file system with the `-o uid=-1,gid=-1` command line option. This will make all files to be owned by the user that launched the file system.

**Comment by mohankumarv2005** [comment] 2019-11-19 05:52
As suggested, I tried above option memfs.exe -o "uid=-1" -o "gid=-1" but no luck. Still I see same issue.

**Comment by billziss-gh** [comment] 2019-11-19 06:41
Did you start memfs from the same account as the one used to access the files in it? Also Make sure that you do not start memfs from an elevated prompt and then try to access the files from a non-elevated Explorer/prompt/etc.

**Comment by mohankumarv2005** [comment] 2019-11-20 04:18
Yes, I have started memfs from non-elevated prompt and also accessing from explorer which is non-elevated too. Also, even I tried to start with elevated it is not helping.

**Comment by billziss-gh** [comment] 2019-11-22 04:02
I am not able to reproduce this. See screenshot below:

![Capture](https://user-images.githubusercontent.com/15330948/69397124-c3a32500-0c99-11ea-91ce-e4a863235336.PNG)

**Comment by mohankumarv2005** [comment] 2019-11-25 05:08
Hi Bill,

Thank you for looking into this. I have attached debug logs of the above scenario. Can you please see if you find anything interesting? Also, is there any other logs or details that you may need to understand what could be issue behind this?

Thanks,
Mohan

[memfs.log](https://github.com/billziss-gh/cgofuse/files/3884924/memfs.log)

**Comment by mohankumarv2005** [comment] 2019-11-27 05:25
We found the root cause for this issue, looks like when we mount with user account whose domain is not same as Machine Domain then we see this problem.

**Comment by billziss-gh** [comment] 2019-12-04 01:14
@mohankumarv2005 

Glad that you have figured out the cause and sorry for being unresponsive this last week as I was away for the Thanksgiving holiday.

I am closing this, but please reopen if you still believe there is a problem.

**Closed by billziss-gh** 2019-12-04 01:14 UTC
